// tokens.ts — GENERATED by scripts/generate-theme.mjs. Do not edit by hand.
//
// Material 3 colour scheme derived from the seed #4C5FD7. Both modes are
// sampled from the same tonal palettes, and every foreground/background pair
// the UI renders is verified against WCAG AA by the generator.
//
// Regenerate with: npm run generate:theme

export const seed = '#4C5FD7';

export type ColorRole =
  | 'primary'
  | 'onPrimary'
  | 'primaryContainer'
  | 'onPrimaryContainer'
  | 'secondary'
  | 'onSecondary'
  | 'secondaryContainer'
  | 'onSecondaryContainer'
  | 'tertiary'
  | 'onTertiary'
  | 'tertiaryContainer'
  | 'onTertiaryContainer'
  | 'error'
  | 'onError'
  | 'errorContainer'
  | 'onErrorContainer'
  | 'success'
  | 'onSuccess'
  | 'successContainer'
  | 'onSuccessContainer'
  | 'warning'
  | 'onWarning'
  | 'warningContainer'
  | 'onWarningContainer'
  | 'background'
  | 'onBackground'
  | 'surface'
  | 'onSurface'
  | 'surfaceVariant'
  | 'onSurfaceVariant'
  | 'outline'
  | 'outlineVariant'
  | 'surfaceContainerLowest'
  | 'surfaceContainerLow'
  | 'surfaceContainer'
  | 'surfaceContainerHigh'
  | 'surfaceContainerHighest'
  | 'inverseSurface'
  | 'inverseOnSurface'
  | 'inversePrimary'
  | 'scrim';

export type ColorScheme = Record<ColorRole, string>;

export const lightScheme: ColorScheme = {
  primary: '#3a53c8',
  onPrimary: '#ffffff',
  primaryContainer: '#e3dfff',
  onPrimaryContainer: '#00164d',
  secondary: '#5e5c76',
  onSecondary: '#ffffff',
  secondaryContainer: '#e3dffe',
  onSecondaryContainer: '#1a192f',
  tertiary: '#824f62',
  onTertiary: '#ffffff',
  tertiaryContainer: '#ffd9e5',
  onTertiaryContainer: '#370a1f',
  error: '#bf0031',
  onError: '#ffffff',
  errorContainer: '#ffdad8',
  onErrorContainer: '#410004',
  success: '#166d2e',
  onSuccess: '#ffffff',
  successContainer: '#a3f5ac',
  onSuccessContainer: '#002202',
  warning: '#825500',
  onWarning: '#ffffff',
  warningContainer: '#ffddb6',
  onWarningContainer: '#271900',
  background: '#f9f9ff',
  onBackground: '#1c1b20',
  surface: '#f9f9ff',
  onSurface: '#1c1b20',
  surfaceVariant: '#e3e1f0',
  onSurfaceVariant: '#474552',
  outline: '#777683',
  outlineVariant: '#c7c5d4',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f4f3fa',
  surfaceContainer: '#eeedf5',
  surfaceContainerHigh: '#e8e7ef',
  surfaceContainerHighest: '#e3e2e9',
  inverseSurface: '#303036',
  inverseOnSurface: '#f1f0f8',
  inversePrimary: '#c4c0ff',
  scrim: '#000000',
};

export const darkScheme: ColorScheme = {
  primary: '#c4c0ff',
  onPrimary: '#00287b',
  primaryContainer: '#003cad',
  onPrimaryContainer: '#e3dfff',
  secondary: '#c7c3e1',
  onSecondary: '#2f2e45',
  secondaryContainer: '#46445d',
  onSecondaryContainer: '#e3dffe',
  tertiary: '#f1b7cb',
  onTertiary: '#4f2134',
  tertiaryContainer: '#68384a',
  onTertiaryContainer: '#ffd9e5',
  error: '#ffb3b0',
  onError: '#680016',
  errorContainer: '#920023',
  onErrorContainer: '#ffdad8',
  success: '#88d991',
  onSuccess: '#003912',
  successContainer: '#00531e',
  onSuccessContainer: '#a3f5ac',
  warning: '#feb958',
  onWarning: '#442b00',
  warningContainer: '#633f00',
  onWarningContainer: '#ffddb6',
  background: '#131318',
  onBackground: '#e3e2e9',
  surface: '#131318',
  onSurface: '#e3e2e9',
  surfaceVariant: '#474552',
  onSurfaceVariant: '#c7c5d4',
  outline: '#918f9d',
  outlineVariant: '#474552',
  surfaceContainerLowest: '#0e0d14',
  surfaceContainerLow: '#1c1b20',
  surfaceContainer: '#201f24',
  surfaceContainerHigh: '#2a292f',
  surfaceContainerHighest: '#35343a',
  inverseSurface: '#e3e2e9',
  inverseOnSurface: '#303036',
  inversePrimary: '#3a53c8',
  scrim: '#000000',
};
